name: Oshun Build

on:
  push:
    branches: [ master ]
    paths:
      - "src/oshun/**"
      - ".github/workflows/oshun.yaml"

  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |-
        cd ./src/oshun/cmd/oshun
        go build -v

    - name: Test
      run: |-
        cd ./src/oshun/cmd/oshun
        go test -v ./...
